### ISSUE TITLE
Create addOxfordComma

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/whats-new-in-emberland#57]
## Background

The `pull-requests` controller has a method called `updateContributorsList` ([see code](https://github.com/ember-learn/whats-new-in-emberland/blob/0d4b187a630abfd21fbd1bc31d976596187aed69/app/controllers/pull-requests.js#L80-L97)).

Given an array of `user`'s (an array of POJOs), the method creates a string and saves it to `contributorsList`, a tracked property. The Ember Times editors can copy-paste that string to a Markdown file, so that a list of links gets rendered in an Ember Times issue:

<img width="640" alt="An Ember Times issue shows a list of contributors" src="https://user-images.githubusercontent.com/16869656/93667732-b687cb80-fa4d-11ea-9317-da57464ef8b7.png">

## Problem

In the screenshot, notice the word `and` that appears between `@toh995` and `Yehuda Katz (@wycats)`. Currently, the editors have to manually add the word.

## TODOs

- [ ] In the controller, create a method called `addOxfordComma`. As input, it takes an array of strings. As output, it returns a string with an Oxford comma.

    In pseudocode,

    ```
    addOxfordComma(words = [])

    Case One: 0, 1 or 2 words
    Returns '', 'X', or 'X and Y'

    Case Two: 3 or more words
    Returns '..., X, Y, and Z'
    ```

- [ ] Add unit tests to check that `addOxfordComma` works.

- [ ] Update the method `updateContributorsList` to call `addOxfordComma`. Check that the conjunction `and` appears when you run the app locally.

- [ ] Update the existing unit test for `updateContributorsList` so that the test passes again.

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue labeled with `Hacktoberfest` in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by JamesS-M** [comment]
I'd love to take this on as a Hacktoberfest contribution! Could you assign me please?

**Comment by ijlee2** [comment]
@JamesS-M Yep, thanks!
