### ISSUE TITLE
Create listUsersInRandomOrder

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/whats-new-in-emberland#58]
## Background

The `pull-requests` controller has a method called `sortUsers` ([see code](https://github.com/ember-learn/whats-new-in-emberland/blob/0d4b187a630abfd21fbd1bc31d976596187aed69/app/controllers/pull-requests.js#L49-L58)).

Given an array of `user`'s (an array of POJOs), the method returns a _new_, sorted array of users (sorted by GitHub handle).

<img width="640" alt="An Ember Times issue shows a list of contributors" src="https://user-images.githubusercontent.com/16869656/93667732-b687cb80-fa4d-11ea-9317-da57464ef8b7.png">

## Problem

The Ember Times editors would like to **list users in a random order** so that they don't unintentionally give some contributors more prominence (or less).

## TODOs

- [ ] In the controller, create a method called `listUsersInRandomOrder`. As input, it takes an array of `user` objects. As output, it returns a new array of `user` objects in a random order ("shuffled").

- [ ] Have a look at the [unit test for `sortUsers`](https://github.com/ember-learn/whats-new-in-emberland/blob/0d4b187a630abfd21fbd1bc31d976596187aed69/tests/unit/controllers/pull-requests-test.js#L95-L135). Create a unit test for `listUsersInRandomOrder`. The test should check that all users in the input array will be present in the output array in _some_ fashion (e.g. match GitHub handles).

- [ ] In the controller, replace `sortUsers` with `listUsersInRandomOrder`. (Don't forget to delete the unit test for `sortUsers`.) Check that the contributors appear in a random order when you run the app locally.

- [ ] A couple of application tests will fail because contributors appear in a random order. Let's look at how to update tests now.

    Have a look at the `<PullRequests::Card>` component's template. Update the test selector `data-test-pull-request` to add the PR title as metadata.

    ```handlebars
    {{!-- Before --}}
    <li data-test-pull-request>...</li>

    {{!-- After --}}
    <li data-test-pull-request="A pull request's title goes here">...</li>
    ```

- [ ] In application tests, instead of referring to a pull request by the array index (e.g. `mergedPRs[0]`), find the pull request that would pass the existing assertion using the `find` helper from `@ember/test-helpers`. Keep in mind that the previous step allows you to find a pull request by its title.

## References

- https://javascript.info/task/shuffle
- https://github.com/emberjs/ember-test-helpers/blob/master/API.md#find

**Comment by ratatatCat** [comment]
Hello, @ijlee2! I am interested in tackling this one if it is still available.

**Comment by ijlee2** [comment]
Hi, @ratatatCat. Thanks for taking an interest in helping out with this issue! Yep, I can assign the issue to you to work on.

I created the issue for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), which will begin in 10 days. If you wanted to participate in the event, would you like to wait on working on a solution until October 1st?

In the meantime, I'd suggest trying out:

- Cloning the repo
- Creating a GitHub personal access token with correct read permission
- Running the Ember app locally to see if you can search for contributors

Trying out these steps would help us discover early issues a new contributor might face during Hacktoberfest. ✨

**Comment by ratatatCat** [comment]
That sounds perfect! Thank you!

**Comment by ijlee2** [comment]
Hi, @ratatatCat. I updated the instructions for installation for clarity.

Just in case, will you check that you forked the repo and create the pull request from your forked repo? If you have any questions, feel free to ask. Thanks!

https://github.com/ember-learn/whats-new-in-emberland#installation

**Comment by ratatatCat** [comment]
Thanks, @ijlee2 ! I am starting on this today.
