### ISSUE TITLE
Install ember-cli-dotenv

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/whats-new-in-emberland#60]
## Background

The app requires an environment variable called `GITHUB_API_KEY` (its value is a GitHub personal access token) for fetching pull requests and contributors (with a higher rate limit).

## Problem

Currently, an Ember Times editor has to either:

- Store `GITHUB_API_KEY` in their `~/.bashrc` (`.zshrc`, etc.), a global file
- Run the app by typing `GITHUB_API_KEY=<secret token> ember s`

Neither option is DX-friendly because this app needs to be run only once in a while (every week or two). I personally end up generating a new token each time because I don't know what the token used to be.

## TODOs

- [ ] Install [ember-cli-dotenv](https://github.com/fivetanley/ember-cli-dotenv) and configure the app to read `GITHUB_API_KEY` from the `.env` file.

- [ ] Add `.env` to `.gitignore`, which stores the list of Git-ignored files.

- [ ] Create `.env-sample` file, which will be committed to GitHub.

- [ ] Update the [Installation](https://github.com/ember-learn/whats-new-in-emberland#installation) section in `README` to explain how to run the app.

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue labeled with `Hacktoberfest` in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by BradLeftley** [comment]
I can pick this up @ijlee2

**Comment by ijlee2** [comment]
@BradLeftley Thanks, it's yours!

**Comment by BradLeftley** [comment]
> @BradLeftley Thanks, it's yours!

Awesome will pick this up over the weekend :)

**Comment by BradLeftley** [comment]
https://github.com/ember-learn/whats-new-in-emberland/pull/61
